version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4
  
workflows:
  build-image-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-reviewsapi'
          extra-build-args: 'sessionName=${SESSION_NAME} sessionSecret=${SESSION_SECRET} maxSessionDays=${MAX_SESSION_DAYS} cache_method=${CACHE_METHOD} region=${AWS_DEFAULT_REGION} userpoolId=${USER_POOL_ID} appClientId=${APP_CLIENT_ID} cognitoOauthUrl=${COGNITO_OAUTH_URL} mds_host=${MDS_HOST} mds_user=${MDS_USER} mds_password=&{MDS_PASSWORD} mds_database=${MDS_DATABASE} reviews_host=${REVIEWS_HOST} reviews_user=${REVIEWS_USER} reviews_password=${REVIEWS_PASSWORD} reviews_database=${REVIEWS_DATABASE}'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - master
      - aws-ecs/deploy-service-update:
          aws-region: AWS_DEFAULT_REGION
          family: 'prodreviewsapi'
          service-name: 'prod-reviewsapi'
          cluster-name: 'dev_reviewsapi_ecs_cluster'
          container-image-name-updates: 'container=reviewsapi,tag=${CIRCLE_SHA1}'
          verify-revision-is-deployed: true
          max-poll-attempts: 30
          poll-interval: 60
          requires:
            - aws-ecr/build-and-push-image
          filters:
            branches:
              only:
                - master
