version: 2.1
orbs:
  aws-ecr: circleci/aws-ecr@6.6.0
  aws-ecs: circleci/aws-ecs@1.0.4
  aws-cli: circleci/aws-cli@0.1.19
  

jobs:
  update-tag:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
      - aws-ecs/update-service:
          family: 'prod-reviewsapi'
          cluster-name: 'dev_reviewsapi_ecs_cluster
          container-image-name-updates: 'container=reviewsapi,tag=${CIRCLE_SHA1}'
  verify-deployment:
    docker:
      - image: 'circleci/python:3.7.1'
    steps:  
      - aws-cli/install
      - aws-cli/setup:
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
     
      - run:
          name: Get last task definition
          command: >
            TASK_DEFINITION_ARN=$(aws ecs describe-task-definition \
                --task-definition prodreviewsapi \
                --output text \
                --query 'taskDefinition.taskDefinitionArn')
            echo "export TASK_DEFINITION_ARN='${TASK_DEFINITION_ARN}'" >>
            $BASH_ENV
      - aws-ecs/verify-revision-is-deployed:
          family: 'prod-reviewsapi'
          cluster-name: 'dev_reviewsapi_ecs_cluster'
          task-definition-arn: '${TASK_DEFINITION_ARN}'
  
workflows:
  build-image-and-push:
    jobs:
      - aws-ecr/build-and-push-image:
          account-url: ECR_ACCOUNT_URL
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_DEFAULT_REGION
          repo: 'coa-reviewsapi'
          tag: '${CIRCLE_SHA1}'
          filters:
            branches:
              only:
                - master
      - update-tag:
          requires:
            - aws-ecr/build-and-push-image
      - verify-deployment:
          requires:
            - update-tag
